import os
import sqlite3
import webbrowser
import html
from datetime import datetime
from PyQt5.QtWidgets import QWidget, QVBoxLayout, QTableWidget, QTableWidgetItem, QPushButton, QMessageBox

from database.db_config import DB_PATH

# Optional: update to the actual logo path in your project (can be relative)
CLINIC_LOGO_PATH = os.path.abspath("DrWs_Dental_Studio_Icon.ico")

CLINIC_NAME = "Dr. N's Dental Studio"
CLINIC_ADDRESS = "First Floor, Chovattukunnel Plaza, Erattupetta Road, Edappady, Pala, Bharananganam, Kerala 686578"
CLINIC_DOCTOR = "Neethu Mathew"


class InventoryReport(QWidget):
    def __init__(self, embed=False):
        super().__init__()
        layout = QVBoxLayout(self)

        self.table = QTableWidget()
        layout.addWidget(self.table)

        export_btn = QPushButton("Export HTML")
        export_btn.clicked.connect(self.export_html)
        layout.addWidget(export_btn)

        self.load_data()
    def showEvent(self, event):
        super().showEvent(event)
        self.load_data()  # Reload patients every time tab is shown
    def load_data(self):
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()

        cursor.execute("""
            SELECT id, item_name, quantity, threshold
            FROM inventory
            ORDER BY item_name ASC
        """)
        rows = cursor.fetchall()
        conn.close()

        self.table.setColumnCount(4)
        self.table.setHorizontalHeaderLabels(["ID", "Item Name", "Quantity", "Threshold"])
        self.table.setRowCount(len(rows))

        for r, row in enumerate(rows):
            for c, col in enumerate(row):
                self.table.setItem(r, c, QTableWidgetItem(str(col)))

    def export_html(self):
        # Ensure Reports folder exists
        reports_dir = os.path.join(os.getcwd(), "Reports")
        os.makedirs(reports_dir, exist_ok=True)

        date_str = datetime.now().strftime("%Y-%m-%d_%H%M%S")
        filename = os.path.join(reports_dir, f"inventory_report_{date_str}.html")

        # Fetch fresh data from DB (keeps file consistent)
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()
        cursor.execute("""
            SELECT id, item_name, quantity, threshold
            FROM inventory
            ORDER BY item_name ASC
        """)
        rows = cursor.fetchall()
        conn.close()

        # Build HTML
        def esc(s):
            return html.escape(str(s))

        html_rows = ""
        for r in rows:
            html_rows += "<tr>"
            html_rows += f"<td>{esc(r[0])}</td>"
            html_rows += f"<td>{esc(r[1])}</td>"
            html_rows += f"<td>{esc(r[2])}</td>"
            html_rows += f"<td>{esc(r[3])}</td>"
            html_rows += "</tr>\n"

        # If you want the logo to appear, ensure CLINIC_LOGO_PATH points to a web-servable image (png/jpg).
        logo_tag = ""
        if os.path.exists(CLINIC_LOGO_PATH):
            # Use file:// URL for local image to display in browser
            logo_tag = f'<img src="file://{CLINIC_LOGO_PATH}" alt="Clinic Logo" style="height:80px;">'

        html_content = f"""<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Inventory Report - {esc(date_str)}</title>
<style>
    body {{ font-family: Arial, Helvetica, sans-serif; margin: 24px; }}
    .header {{ display:flex; align-items:center; gap:16px; }}
    .clinic-info {{ line-height:1.1; }}
    h1 {{ margin:0; font-size:20px; }}
    .meta {{ margin-top:6px; color:#333; font-size:13px; }}
    table {{ width:100%; border-collapse:collapse; margin-top:16px; }}
    th, td {{ border:1px solid #ddd; padding:8px; text-align:left; }}
    th {{ background:#f2f2f2; }}
    .low-stock {{ background:#ffe6e6; }}
    .footer {{ margin-top:18px; font-size:12px; color:#666; }}
</style>
</head>
<body>
    <div class="header">
        {logo_tag}
        <div class="clinic-info">
            <h1>{esc(CLINIC_NAME)}</h1>
            <div class="meta">{esc(CLINIC_ADDRESS)}<br>Doctor: {esc(CLINIC_DOCTOR)}</div>
            <div class="meta">Report generated: {esc(date_str)}</div>
        </div>
    </div>

    <table>
        <thead>
            <tr><th>ID</th><th>Item Name</th><th>Quantity</th><th>Threshold</th></tr>
        </thead>
        <tbody>
            {html_rows}
        </tbody>
    </table>

    <div class="footer">Generated by Dr. N's Dental Studio Management System</div>
</body>
</html>
"""

        try:
            with open(filename, "w", encoding="utf-8") as f:
                f.write(html_content)
        except Exception as e:
            QMessageBox.warning(self, "Export HTML", f"Failed to write HTML file:\n{e}")
            return

        # Open the generated HTML in default browser
        try:
            webbrowser.open(f"file://{os.path.abspath(filename)}")
        except Exception:
            # Not fatal — show a message with the path
            pass

        QMessageBox.information(self, "Export HTML", f"Inventory report exported successfully as:\n{filename}")
